version: '3.9'
services:
  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      #本番時コメントアウトを元に戻す
      # args:
      #   NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    env_file:
      - .env
    tty: true

  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    tty: true
  
  app-db:
    image: mysql:8
    command: --collation-server=utf8mb4_0900_bin --transaction-isolation=READ-COMMITTED
    restart: always
    env_file:
      - .env
    ports:
      - 53306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  frontend_node_modules:
  mysql_data:
